services:
  jupyter:
    container_name: ${DOCKER_CONTAINER}
    hostname: ${DOCKER_CONTAINER}
    restart: always
    image: ${REGISTRY}:${REGISTRY_PORT}/${DOCKER_IMAGE}:${TAG}
    env_file:
      - .env
    volumes:
      - ./notebooks:/src/notebooks
    ports:
      - "8888:8888"
    logging:
      driver: 'json-file'
      options:
        max-size: 50m
        max-file: '2'